version: "1.0"
info:
  model: int-scaffold
packages:
- name: KUSIGitExternalUCProject
  gitServerName: KusiGITExternalUseCase
  gitUrl: https://github.com/siqagituser/KUSIGitExternalUCProject
  gitUsername: siqagituser
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  gitServerName: vidiJan24
  gitUrl: https://github.com/vijetadixit
  gitUsername: vijetadixit
  gitBranch: Test
services:
- serviceName: project.kusigitexternaluc.integrations:TPPCRTExGitUC
  packages:
  - name: KUSIGitExternalUCProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Basics_1:ComplexFS
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Basics_1:Basic_Flow
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: pub.math:divideInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.795
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.795
- serviceName: pub.math:subtractInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.795
- serviceName: pub.math:multiplyIntList
  packages:
  - name: WmPublic
    version: 11.0.0.0.795
- serviceName: Basics_1:mapservice
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Basics_1:TryCatch
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Map_1:TestFlow
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: REST_1_1.CurrentDateAndTime:_get
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.795
- serviceName: pub.string:objectToString
  packages:
  - name: WmPublic
    version: 11.0.0.0.795
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.795
- serviceName: SOAP_1_1:showDateAndTime
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
