version: "1.0"
info:
  model: int-scaffold
packages:
- name: KUSIGitExternalUCProject
  gitServerName: KusiGITExternalUseCase
  gitUrl: https://github.com/siqagituser/KUSIGitExternalUCProject
  gitUsername: siqagituser
  gitBranch: main
