version: "1.0"
info:
  model: int-scaffold
packages:
- name: KUSIGitExternalUCProject
  gitServerName: KusiGITExternalUseCase
  gitUrl: https://github.com/siqagituser/KUSIGitExternalUCProject
  gitUsername: siqagituser
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  gitServerName: vidiJan24
  gitUrl: https://github.com/vijetadixit
  gitUsername: vijetadixit
  gitBranch: Test
